sets.exported={
    main="Bolelabunga",
    sub="Genbu's Shield",
    range="Dunna",
    head="Azimuth Hood +1",
    body={ name="Hagondes Coat +1", augments={'Phys. dmg. taken -4%',}},
    hands={ name="Bagua Mitaines", augments={'Enhances "Curative Recantation" effect',}},
    legs="Assid. Pants +1",
    feet={ name="Telchine Pigaches", augments={'Enh. Mag. eff. dur. +8',}},
    neck="Incanter's Torque",
    waist="Austerity Belt",
    left_ear="Magnetic Earring",
    right_ear="Loquac. Earring",
    left_ring="Defending Ring",
    right_ring="Lebeche Ring",
    back={ name="Lifestream Cape", augments={'Geomancy Skill +4','Indi. eff. dur. +17','Pet: Damage taken -5%','Damage taken-5%',}},
}