sets.exported={
    main="Kaja Knife",
    sub="Beveler's Shield",
    ammo="Yetshila",
    head="Turms Cap",
    body="Tanner's Apron",
    hands="Tanner's Gloves",
    legs="Pill. Culottes +3",
    feet="Jute Boots +1",
    neck="Tanner's Torque",
    waist="Patentia Sash",
    left_ear="Sherida Earring",
    right_ear={ name="Moonshade Earring", augments={'Accuracy+4','TP Bonus +250',}},
    left_ring="Orvail Ring",
    right_ring="Regal Ring",
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','DEX+10','Crit.hit rate+10',}},
}