sets.exported={
    main="Naegling",
    sub="Tauret",
    range={ name="Fomalhaut", augments={'Path: A',}},
    head="Malignance Chapeau",
    body={ name="Herculean Vest", augments={'Mag. Acc.+20 "Mag.Atk.Bns."+20','Crit.hit rate+2','STR+5','Mag. Acc.+12','"Mag.Atk.Bns."+15',}},
    hands="Malignance Gloves",
    legs={ name="Herculean Trousers", augments={'Mag. Acc.+19 "Mag.Atk.Bns."+19','Weapon skill damage +4%','Mag. Acc.+15','"Mag.Atk.Bns."+1',}},
    feet={ name="Herculean Boots", augments={'Accuracy+24 Attack+24','Damage taken-2%','STR+7','Accuracy+11','Attack+15',}},
    neck="Combatant's Torque",
    waist="Flume Belt",
    left_ear="Cessance Earring",
    right_ear="Loquac. Earring",
    left_ring="Endorsement Ring",
    back={ name="Mecisto. Mantle", augments={'Cap. Point+49%','MP+23','Attack+2','DEF+1',}},
}