sets.exported={
    main={ name="Malevolence", augments={'INT+7','Mag. Acc.+3','"Mag.Atk.Bns."+5','"Fast Cast"+2',}},
    sub="Blurred Knife +1",
    range={ name="Sparrowhawk", augments={'DMG:+12','Arching Arrow:DMG:+10%',}},
    ammo="Chrono Arrow",
    head="Malignance Chapeau",
    body="Malignance Tabard",
    hands="Malignance Gloves",
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet={ name="Herculean Boots", augments={'Accuracy+26','"Triple Atk."+4','DEX+9','Attack+1',}},
    neck="Loricate Torque +1",
    waist="Flume Belt",
    left_ear="Etiolation Earring",
    right_ear="Infused Earring",
    left_ring="Defending Ring",
    right_ring="Sheltered Ring",
    back="Moonlight cape",
}