sets.exported={
    main="Naegling",
    sub="Tauret",
    range={ name="Anarchy +2", augments={'Delay:+60','TP Bonus +1000',}},
    head="Malignance Chapeau",
    body="Malignance Tabard",
    hands="Malignance Gloves",
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet="Malignance Boots",
    neck={ name="Loricate Torque +1", augments={'Path: A',}},
    waist="Chr. Bul. Pouch",
    left_ear="Etiolation Earring",
    right_ear="Infused Earring",
    left_ring="Sheltered Ring",
    right_ring="Defending Ring",
    back={ name="Camulus's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+5','Weapon skill damage +10%','Phys. dmg. taken-10%',}},
}