sets.exported={
    main="Daybreak",
    sub="Genmei Shield",
    range={ name="Nibiru Harp", augments={'Mag. Evasion+20','Phys. dmg. taken -3','Magic dmg. taken -3',}},
    head={ name="Telchine Cap", augments={'Enh. Mag. eff. dur. +8',}},
    body={ name="Telchine Chas.", augments={'Enh. Mag. eff. dur. +9',}},
    hands={ name="Telchine Gloves", augments={'Enh. Mag. eff. dur. +9',}},
    legs={ name="Telchine Braconi", augments={'Enh. Mag. eff. dur. +9',}},
    feet={ name="Telchine Pigaches", augments={'Mag. Acc.+20','"Fast Cast"+4','Enh. Mag. eff. dur. +8',}},
    neck="Loricate Torque +1",
    waist="Flume Belt",
    left_ear="Etiolation Earring",
    right_ear="Infused Earring",
    left_ring="Defending Ring",
    right_ring="Moonlight Ring",
    back="Moonbeam Cape",
}