sets.exported={
    main={ name="Gandring", augments={'Path: C',}},
    sub={ name="Twashtar", augments={'Path: A',}},
    ammo="Yamarang",
    head="Malignance Chapeau",
    body="Pillager's Vest +3",
    hands={ name="Adhemar Wrist. +1", augments={'DEX+12','AGI+12','Accuracy+20',}},
    legs="Pill. Culottes +3",
    feet="Turms Leggings +1",
    neck={ name="Asn. Gorget +2", augments={'Path: A',}},
    waist="Flume Belt",
    left_ear="Infused Earring",
    right_ear="Telos Earring",
    left_ring="Moonlight Ring",
    right_ring="Moonlight Ring",
    back={ name="Toutatis's Cape", augments={'AGI+20','Eva.+20 /Mag. Eva.+20','Evasion+10','"Store TP"+10','Phys. dmg. taken-10%',}},
}