sets.exported={
    main="Aeneas",
    sub="Twashtar",
    ammo="Ginsen",
    head={ name="Herculean Helm", augments={'Accuracy+28','Weapon skill damage +3%','DEX+9','Attack+15',}},
    body="Pillager's Vest +3",
    hands={ name="Adhemar Wrist. +1", augments={'DEX+12','AGI+12','Accuracy+20',}},
    legs="Pill. Culottes +3",
    feet="Jute Boots +1",
    neck="Bathy Choker",
    waist="Chiner's Belt +1",
    left_ear="Sherida Earring",
    right_ear="Tripudio Earring",
    left_ring="Sheltered Ring",
    right_ring="Paguroidea Ring",
    back={ name="Mecisto. Mantle", augments={'Cap. Point+49%','MP+23','Attack+2','DEF+1',}},
}