sets.exported={
    main="Naegling",
    sub={ name="Machaera +2", augments={'TP Bonus +1000',}},
    ammo="Staunch Tathlum +1",
    head={ name="Taeon Chapeau", augments={'"Repair" potency +5%','Phalanx +3',}},
    body={ name="Taeon Tabard", augments={'Attack+23','"Dual Wield"+5','Phalanx +3',}},
    hands={ name="Taeon Gloves", augments={'Phalanx +3',}},
    legs={ name="Taeon Tights", augments={'Accuracy+20 Attack+20','"Triple Atk."+2','Phalanx +3',}},
    feet={ name="Taeon Boots", augments={'Phalanx +3',}},
    neck="Incanter's Torque",
    waist="Embla Sash",
    left_ear="Mimir Earring",
    right_ear="Augment. Earring",
    left_ring="Stikini Ring +1",
    right_ring="Stikini Ring +1",
    back={ name="Fi Follet Cape +1", augments={'Path: A',}},
}