sets.exported={
    main="Aeneas",
    sub="Twashtar",
    range="Gjallarhorn",
    head="Aya. Zucchetto +1",
    body="Ayanmo Corazza +1",
    hands="Aya. Manopolas +1",
    legs="Aya. Cosciales +1",
    feet="Aya. Gambieras +1",
    neck="Subtlety Spec.",
    waist="Kentarch Belt +1",
    left_ear="Digni. Earring",
    right_ear="Suppanomimi",
    left_ring="Rajas Ring",
    right_ring="Ramuh Ring +1",
    back="Ground. Mantle +1",
}