sets.exported={
    main="Sequence",
    sub={ name="Vampirism", augments={'STR+8','INT+9','"Occult Acumen"+8','DMG:+14',}},
    ammo="Ginsen",
    head="Aya. Zucchetto +1",
    hands="Umuthi Gloves",
    legs={ name="Carmine Cuisses +1", augments={'Accuracy+20','Attack+12','"Dual Wield"+6',}},
    feet={ name="Herculean Boots", augments={'Accuracy+26','"Triple Atk."+4','DEX+9','Attack+1',}},
    neck="Loricate Torque +1",
    waist="Flume Belt",
    left_ear="Infused Earring",
    right_ear="Loquac. Earring",
    left_ring="Defending Ring",
    right_ring="Patricius Ring",
    back="Moonbeam Cape",
}