sets.exported={
    main={ name="Vajra", augments={'Path: A',}},
    sub={ name="Fusetto +3", augments={'TP Bonus +1000',}},
    ammo="Sapience Orb",
    head={ name="Herculean Helm", augments={'"Mag.Atk.Bns."+24','"Fast Cast"+6','STR+7','Mag. Acc.+14',}},
    body="Dread Jupon",
    hands={ name="Leyline Gloves", augments={'Accuracy+15','Mag. Acc.+15','"Mag.Atk.Bns."+15','"Fast Cast"+3',}},
    legs={ name="Rawhide Trousers", augments={'MP+43','"Fast Cast"+4',}},
    feet="Jute Boots +1",
    neck="Voltsurge Torque",
    waist="Flume Belt",
    left_ear="Etiolation Earring",
    right_ear="Loquac. Earring",
    left_ring="Prolix Ring",
    right_ring="Sheltered Ring",
    back="Moonbeam Cape",
}